#undef TAPPING_TERM
#define TAPPING_TERM 175

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 10

#define SERIAL_NUMBER "BNJ7W/qmnNv5"
#define LAYER_STATE_16BIT

#define TAPPING_TERM_PER_KEY
